//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTA.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private int creditField;
        
        private System.DateTime sDateField;
        
        private System.DateTime eDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cid {
            get {
                return this.cidField;
            }
            set {
                if ((object.ReferenceEquals(this.cidField, value) != true)) {
                    this.cidField = value;
                    this.RaisePropertyChanged("cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int credit {
            get {
                return this.creditField;
            }
            set {
                if ((this.creditField.Equals(value) != true)) {
                    this.creditField = value;
                    this.RaisePropertyChanged("credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime sDate {
            get {
                return this.sDateField;
            }
            set {
                if ((this.sDateField.Equals(value) != true)) {
                    this.sDateField = value;
                    this.RaisePropertyChanged("sDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime eDate {
            get {
                return this.eDateField;
            }
            set {
                if ((this.eDateField.Equals(value) != true)) {
                    this.eDateField = value;
                    this.RaisePropertyChanged("eDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledCourse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ScheduledCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NTA.ServiceReference1.Member TrainerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NTA.ServiceReference1.centre CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NTA.ServiceReference1.Course courseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public NTA.ServiceReference1.Member Trainer {
            get {
                return this.TrainerField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainerField, value) != true)) {
                    this.TrainerField = value;
                    this.RaisePropertyChanged("Trainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NTA.ServiceReference1.centre Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public NTA.ServiceReference1.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mem_tpField;
        
        private System.DateTime dobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mem_tp {
            get {
                return this.mem_tpField;
            }
            set {
                if ((object.ReferenceEquals(this.mem_tpField, value) != true)) {
                    this.mem_tpField = value;
                    this.RaisePropertyChanged("mem_tp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime dob {
            get {
                return this.dobField;
            }
            set {
                if ((this.dobField.Equals(value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="centre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class centre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int roomNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int roomNo {
            get {
                return this.roomNoField;
            }
            set {
                if ((this.roomNoField.Equals(value) != true)) {
                    this.roomNoField = value;
                    this.RaisePropertyChanged("roomNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.coursesStreamSoap")]
    public interface coursesStreamSoap {
        
        // CODEGEN: Generating message contract since element name allCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allCourse", ReplyAction="*")]
        NTA.ServiceReference1.allCourseResponse allCourse(NTA.ServiceReference1.allCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<NTA.ServiceReference1.allCourseResponse> allCourseAsync(NTA.ServiceReference1.allCourseRequest request);
        
        // CODEGEN: Generating message contract since element name campus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoursesByLocation", ReplyAction="*")]
        NTA.ServiceReference1.CoursesByLocationResponse CoursesByLocation(NTA.ServiceReference1.CoursesByLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoursesByLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<NTA.ServiceReference1.CoursesByLocationResponse> CoursesByLocationAsync(NTA.ServiceReference1.CoursesByLocationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allCourse", Namespace="http://tempuri.org/", Order=0)]
        public NTA.ServiceReference1.allCourseRequestBody Body;
        
        public allCourseRequest() {
        }
        
        public allCourseRequest(NTA.ServiceReference1.allCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class allCourseRequestBody {
        
        public allCourseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public NTA.ServiceReference1.allCourseResponseBody Body;
        
        public allCourseResponse() {
        }
        
        public allCourseResponse(NTA.ServiceReference1.allCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class allCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NTA.ServiceReference1.Course[] allCourseResult;
        
        public allCourseResponseBody() {
        }
        
        public allCourseResponseBody(NTA.ServiceReference1.Course[] allCourseResult) {
            this.allCourseResult = allCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CoursesByLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CoursesByLocation", Namespace="http://tempuri.org/", Order=0)]
        public NTA.ServiceReference1.CoursesByLocationRequestBody Body;
        
        public CoursesByLocationRequest() {
        }
        
        public CoursesByLocationRequest(NTA.ServiceReference1.CoursesByLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CoursesByLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string campus;
        
        public CoursesByLocationRequestBody() {
        }
        
        public CoursesByLocationRequestBody(string campus) {
            this.campus = campus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CoursesByLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CoursesByLocationResponse", Namespace="http://tempuri.org/", Order=0)]
        public NTA.ServiceReference1.CoursesByLocationResponseBody Body;
        
        public CoursesByLocationResponse() {
        }
        
        public CoursesByLocationResponse(NTA.ServiceReference1.CoursesByLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CoursesByLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NTA.ServiceReference1.ScheduledCourse[] CoursesByLocationResult;
        
        public CoursesByLocationResponseBody() {
        }
        
        public CoursesByLocationResponseBody(NTA.ServiceReference1.ScheduledCourse[] CoursesByLocationResult) {
            this.CoursesByLocationResult = CoursesByLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface coursesStreamSoapChannel : NTA.ServiceReference1.coursesStreamSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class coursesStreamSoapClient : System.ServiceModel.ClientBase<NTA.ServiceReference1.coursesStreamSoap>, NTA.ServiceReference1.coursesStreamSoap {
        
        public coursesStreamSoapClient() {
        }
        
        public coursesStreamSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public coursesStreamSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coursesStreamSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coursesStreamSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTA.ServiceReference1.allCourseResponse NTA.ServiceReference1.coursesStreamSoap.allCourse(NTA.ServiceReference1.allCourseRequest request) {
            return base.Channel.allCourse(request);
        }
        
        public NTA.ServiceReference1.Course[] allCourse() {
            NTA.ServiceReference1.allCourseRequest inValue = new NTA.ServiceReference1.allCourseRequest();
            inValue.Body = new NTA.ServiceReference1.allCourseRequestBody();
            NTA.ServiceReference1.allCourseResponse retVal = ((NTA.ServiceReference1.coursesStreamSoap)(this)).allCourse(inValue);
            return retVal.Body.allCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTA.ServiceReference1.allCourseResponse> NTA.ServiceReference1.coursesStreamSoap.allCourseAsync(NTA.ServiceReference1.allCourseRequest request) {
            return base.Channel.allCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTA.ServiceReference1.allCourseResponse> allCourseAsync() {
            NTA.ServiceReference1.allCourseRequest inValue = new NTA.ServiceReference1.allCourseRequest();
            inValue.Body = new NTA.ServiceReference1.allCourseRequestBody();
            return ((NTA.ServiceReference1.coursesStreamSoap)(this)).allCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTA.ServiceReference1.CoursesByLocationResponse NTA.ServiceReference1.coursesStreamSoap.CoursesByLocation(NTA.ServiceReference1.CoursesByLocationRequest request) {
            return base.Channel.CoursesByLocation(request);
        }
        
        public NTA.ServiceReference1.ScheduledCourse[] CoursesByLocation(string campus) {
            NTA.ServiceReference1.CoursesByLocationRequest inValue = new NTA.ServiceReference1.CoursesByLocationRequest();
            inValue.Body = new NTA.ServiceReference1.CoursesByLocationRequestBody();
            inValue.Body.campus = campus;
            NTA.ServiceReference1.CoursesByLocationResponse retVal = ((NTA.ServiceReference1.coursesStreamSoap)(this)).CoursesByLocation(inValue);
            return retVal.Body.CoursesByLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTA.ServiceReference1.CoursesByLocationResponse> NTA.ServiceReference1.coursesStreamSoap.CoursesByLocationAsync(NTA.ServiceReference1.CoursesByLocationRequest request) {
            return base.Channel.CoursesByLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTA.ServiceReference1.CoursesByLocationResponse> CoursesByLocationAsync(string campus) {
            NTA.ServiceReference1.CoursesByLocationRequest inValue = new NTA.ServiceReference1.CoursesByLocationRequest();
            inValue.Body = new NTA.ServiceReference1.CoursesByLocationRequestBody();
            inValue.Body.campus = campus;
            return ((NTA.ServiceReference1.coursesStreamSoap)(this)).CoursesByLocationAsync(inValue);
        }
    }
}
